name: CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.2
          check-latest: true
        id: go

      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: start postgres
        run: make postgres

      - name: sleep
        run: sleep 5
    
      - name: execute the server
        run: make serve &

      - name: sleep to allow integration tests pass
        run: sleep 2

      - name: integration & unit tests
        run: go test -count=1 -p=1 -tags=integration  -v ./...